version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
