---
- name: Download and install Composer
  hosts: server_belajar_ansible
  become: true

  tasks:
    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: 0644

    - name: Verify Composer installer hash
      shell: curl -sS https://composer.github.io/installer.sig
      register: composer_hash_output

    - name: Check if Composer installer is corrupt
      block:
        - name: Verify SHA384 hash
          shell: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '{{ composer_hash_output.stdout }}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          register: composer_verification_output

        - name: Delete corrupted installer if necessary
          file:
            path: /tmp/composer-setup.php
            state: absent
          when: "'Installer corrupt' in composer_verification_output.stdout"

    - name: Install Composer
      shell: sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
