---
- name: Install Node.js 21.x
  hosts: all
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Install ca-certificates, curl, and gnupg
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download NodeSource GPG key
      get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource-repo.gpg
        mode: '0644'

    - name: Add NodeSource repository to apt sources list
      copy:
        dest: /etc/apt/sources.list.d/nodesource.list
        content: |
          deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_21.x nodistro main
        owner: root
        group: root
        mode: '0644'

    - name: Update apt package cache again
      apt:
        update_cache: true

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
